### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by yy9568** [JKBox/YOLOv3-quadrangle#2]
It seems that torch version does not match, which version do you use? I used torch 0.4.1 and met this problem.

**Comment by yy9568** [comment]
@JKBox When I print loss, I got `tensor([0.], device='cuda:0')`

**Comment by JKBox** [comment]
> It seems that torch version does not match, which version do you use? I used torch 0.4.1 and met this problem.

I forget which torch version I used, you can try a higher version, which is downward compatible.

**Comment by yy9568** [comment]
@JKBox Hey! I solved it by update torch version to 1.1.0, and I had trained it successfully on my dataset, the result looks good enough. Thank you very much and thanks for the code sharing, too!

**Comment by vineeth357** [comment]
> @JKBox Hey! I solved it by update the torch version to 1.1.0, and I had trained it successfully on my dataset, the result looks good enough. Thank you very much and thanks for the code sharing, too!

hi, 
can u help me by answering some questions??
1. format of the dataset to use?? (ex: Coco, JSON etc)
2. In which directory we have to place our dataset?
3. format of annotations?
4. any problem in training for u and suggestions for that??
 thanks before :)
