### ISSUE TITLE
The way of coordinates regression  repo used in whether is same with  Deep Matching Prior Network used in

### ISSUE THREAD

**Issue by yy9568** [JKBox/YOLOv3-quadrangle#5]
@JKBox  [link](https://arxiv.org/abs/1703.01425)

**Comment by JKBox** [comment]
yes, it's roughly the same

**Comment by JKBox** [comment]
> @JKBox [link](https://arxiv.org/abs/1703.01425)

yes, it's roughly the same

**Comment by JKBox** [comment]
> @JKBox [link](https://arxiv.org/abs/1703.01425)

yes, it's roughly the same

**Comment by yy9568** [comment]
@JKBox Hi, thank you for your reply. Is there any blog you write to explain how it works properly for this repository? I have been read your codes for several days, actually, in the original paper, computing IoU of Polygons use `Shared Monte-Carlo method `, but from your codes I got that you used `sharply` to compute the IoU, So I have a question that, `sharply` module does that job may slower than `Shared Monte-Carlo `, am I right? sharply can not process cuda tensor actually. So I want to contribute this repository to implement ``Shared Monte-Carlo`, could you help me or give some suggestions? Sincerely, best wishes~

**Comment by JKBox** [comment]
> @JKBox Hi, thank you for your reply. Is there any blog you write to explain how it works properly for this repository? I have been read your codes for several days, actually, in the original paper, computing IoU of Polygons use `Shared Monte-Carlo method `, but from your codes I got that you used `sharply` to compute the IoU, So I have a question that, `sharply` module does that job may slower than `Shared Monte-Carlo `, am I right? sharply can not process cuda tensor actually. So I want to contribute this repository to implement ``Shared Monte-Carlo`, could you help me or give some suggestions? Sincerely, best wishes~

Thank you for your interest. I implemented `Shapely` module just for convenience, and it's indeed much slower than `Shared Monte-Carlo method`. Sorry that I can't give you any suggestions cause I don't know it well. You can try it, good luck.

**Comment by Jinglei5** [comment]
@zhouyuangan 
hi~Did you find the implementation of `Shared Monte-Carlo` yet? Could you share the repository or link? Thanks a lot!

**Comment by yy9568** [comment]
> @zhouyuangan
> hi~Did you find the implementation of `Shared Monte-Carlo` yet? Could you share the repository or link? Thanks a lot!

Sorry, I had sent an email to author but no response I got, and I gave up my plan. So I'd like to compute IoU and overlaps between rotated boxes. It's easier, thanks.
